### ISSUE TITLE
Mail notification with TLS and authentication not possible

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/crowbar-escm#45]
Mail notification works fine with internal mail servers and without encryption.
However when configuring an external mail server using TLS and authentication the OSCM setup gets unusable.
For instance, when setting smtp.gmail.com via port 587, OSCM fails with following error:
"javax.mail.MessagingException: Unable to obtain SASL authenticator".

Next steps
 * Check what is required to enable usage of external mail servers
 * Check what is required to make TLS and authentication working
 * In case of doubts, test again the given case to exclude firewall or configuration issues

**Comment by shimizuf** [comment]
This is most likely to be fixed in the Docker code. Therefore created servicecatalog/oscm-dockerbuild/issues/111 and closing this as a duplicate.
